version: '3'
services:
  resource_micro:
    container_name: 'resource_micro'
    build: .
    command: python run.py
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"
    restart: on-failure
    depends_on:
      - rabbitmq
      - db
    networks: 
      app_net:
        ipv4_address: 172.16.238.10
  db:
    image: mongo
    container_name: 'mongo'
    ports: 
      - "27017:27017"
    networks: 
      app_net:
        ipv4_address: 172.16.238.20
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    hostname: rabbitmq
    ports: 
      - "5672:5672"
    networks: 
      app_net:
        ipv4_address: 172.16.238.30

networks: 
  app_net:
    ipam: 
      driver: default
      config: 
        - subnet: "172.16.238.0/16"