# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/services/currency/currency.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/services/currency/currency.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$app/services/currency/currency.proto\"\x07\n\x05\x45mpty\"\x1f\n\x11\x43urrencyIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\xaa\x01\n\x14\x43urrencyNotIdRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x12(\n\x04type\x18\x04 \x01(\x0e\x32\x1a.CurrencyNotIdRequest.Type\x12\x0e\n\x06symbol\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x01\"\x1c\n\x04Type\x12\x08\n\x04\x46IAT\x10\x00\x12\n\n\x06\x43RYPTO\x10\x01\"\xac\x01\n\x0f\x43urrencyRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x63olor\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\x12#\n\x04type\x18\x05 \x01(\x0e\x32\x15.CurrencyRequest.Type\x12\x0e\n\x06symbol\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\x01\"\x1c\n\x04Type\x12\x08\n\x04\x46IAT\x10\x00\x12\n\n\x06\x43RYPTO\x10\x01\"6\n\x10\x43urrencyResponse\x12\"\n\x08\x63urrency\x18\x01 \x01(\x0b\x32\x10.CurrencyRequest\">\n\x18\x43urrencyMultipleResponse\x12\"\n\x08\x63urrency\x18\x01 \x03(\x0b\x32\x10.CurrencyRequest2\xf7\x01\n\x08\x43urrency\x12+\n\x06getAll\x12\x06.Empty\x1a\x19.CurrencyMultipleResponse\x12,\n\x03get\x12\x12.CurrencyIdRequest\x1a\x11.CurrencyResponse\x12\x30\n\x04save\x12\x15.CurrencyNotIdRequest\x1a\x11.CurrencyResponse\x12-\n\x06update\x12\x10.CurrencyRequest\x1a\x11.CurrencyResponse\x12/\n\x06\x64\x65lete\x12\x12.CurrencyIdRequest\x1a\x11.CurrencyResponseb\x06proto3'
)



_CURRENCYNOTIDREQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='CurrencyNotIdRequest.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIAT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRYPTO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=225,
  serialized_end=253,
)
_sym_db.RegisterEnumDescriptor(_CURRENCYNOTIDREQUEST_TYPE)

_CURRENCYREQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='CurrencyRequest.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIAT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRYPTO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=225,
  serialized_end=253,
)
_sym_db.RegisterEnumDescriptor(_CURRENCYREQUEST_TYPE)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=47,
)


_CURRENCYIDREQUEST = _descriptor.Descriptor(
  name='CurrencyIdRequest',
  full_name='CurrencyIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CurrencyIdRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=80,
)


_CURRENCYNOTIDREQUEST = _descriptor.Descriptor(
  name='CurrencyNotIdRequest',
  full_name='CurrencyNotIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CurrencyNotIdRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='CurrencyNotIdRequest.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active', full_name='CurrencyNotIdRequest.active', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='CurrencyNotIdRequest.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='CurrencyNotIdRequest.symbol', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='CurrencyNotIdRequest.price', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CURRENCYNOTIDREQUEST_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=253,
)


_CURRENCYREQUEST = _descriptor.Descriptor(
  name='CurrencyRequest',
  full_name='CurrencyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CurrencyRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='CurrencyRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='CurrencyRequest.color', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active', full_name='CurrencyRequest.active', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='CurrencyRequest.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='CurrencyRequest.symbol', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='CurrencyRequest.price', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CURRENCYREQUEST_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=428,
)


_CURRENCYRESPONSE = _descriptor.Descriptor(
  name='CurrencyResponse',
  full_name='CurrencyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='CurrencyResponse.currency', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=484,
)


_CURRENCYMULTIPLERESPONSE = _descriptor.Descriptor(
  name='CurrencyMultipleResponse',
  full_name='CurrencyMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='CurrencyMultipleResponse.currency', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=548,
)

_CURRENCYNOTIDREQUEST.fields_by_name['type'].enum_type = _CURRENCYNOTIDREQUEST_TYPE
_CURRENCYNOTIDREQUEST_TYPE.containing_type = _CURRENCYNOTIDREQUEST
_CURRENCYREQUEST.fields_by_name['type'].enum_type = _CURRENCYREQUEST_TYPE
_CURRENCYREQUEST_TYPE.containing_type = _CURRENCYREQUEST
_CURRENCYRESPONSE.fields_by_name['currency'].message_type = _CURRENCYREQUEST
_CURRENCYMULTIPLERESPONSE.fields_by_name['currency'].message_type = _CURRENCYREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['CurrencyIdRequest'] = _CURRENCYIDREQUEST
DESCRIPTOR.message_types_by_name['CurrencyNotIdRequest'] = _CURRENCYNOTIDREQUEST
DESCRIPTOR.message_types_by_name['CurrencyRequest'] = _CURRENCYREQUEST
DESCRIPTOR.message_types_by_name['CurrencyResponse'] = _CURRENCYRESPONSE
DESCRIPTOR.message_types_by_name['CurrencyMultipleResponse'] = _CURRENCYMULTIPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'app.services.currency.currency_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

CurrencyIdRequest = _reflection.GeneratedProtocolMessageType('CurrencyIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CURRENCYIDREQUEST,
  '__module__' : 'app.services.currency.currency_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyIdRequest)
  })
_sym_db.RegisterMessage(CurrencyIdRequest)

CurrencyNotIdRequest = _reflection.GeneratedProtocolMessageType('CurrencyNotIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _CURRENCYNOTIDREQUEST,
  '__module__' : 'app.services.currency.currency_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyNotIdRequest)
  })
_sym_db.RegisterMessage(CurrencyNotIdRequest)

CurrencyRequest = _reflection.GeneratedProtocolMessageType('CurrencyRequest', (_message.Message,), {
  'DESCRIPTOR' : _CURRENCYREQUEST,
  '__module__' : 'app.services.currency.currency_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyRequest)
  })
_sym_db.RegisterMessage(CurrencyRequest)

CurrencyResponse = _reflection.GeneratedProtocolMessageType('CurrencyResponse', (_message.Message,), {
  'DESCRIPTOR' : _CURRENCYRESPONSE,
  '__module__' : 'app.services.currency.currency_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyResponse)
  })
_sym_db.RegisterMessage(CurrencyResponse)

CurrencyMultipleResponse = _reflection.GeneratedProtocolMessageType('CurrencyMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _CURRENCYMULTIPLERESPONSE,
  '__module__' : 'app.services.currency.currency_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyMultipleResponse)
  })
_sym_db.RegisterMessage(CurrencyMultipleResponse)



_CURRENCY = _descriptor.ServiceDescriptor(
  name='Currency',
  full_name='Currency',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=551,
  serialized_end=798,
  methods=[
  _descriptor.MethodDescriptor(
    name='getAll',
    full_name='Currency.getAll',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CURRENCYMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='Currency.get',
    index=1,
    containing_service=None,
    input_type=_CURRENCYIDREQUEST,
    output_type=_CURRENCYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='Currency.save',
    index=2,
    containing_service=None,
    input_type=_CURRENCYNOTIDREQUEST,
    output_type=_CURRENCYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='Currency.update',
    index=3,
    containing_service=None,
    input_type=_CURRENCYREQUEST,
    output_type=_CURRENCYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='Currency.delete',
    index=4,
    containing_service=None,
    input_type=_CURRENCYIDREQUEST,
    output_type=_CURRENCYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCY)

DESCRIPTOR.services_by_name['Currency'] = _CURRENCY

# @@protoc_insertion_point(module_scope)
